### ISSUE TITLE
Bring back reactions

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/ORION#119]
we used to have them from KEGG.  We stopped for licensing reasons.   We need to pull in reactome or something.  The confusing part is how to handle that reactions are bidirectional etc.

**Comment by cbizon** [comment]
We need metabolites one way or another...

**Comment by DnlRKorn** [comment]
This issue is being handled through the integration of REACTOME. 

https://github.com/RobokopU24/ORION/issues/146
