### ISSUE TITLE
Where is this GWAS Catalog data

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/ORION#121]
https://www.ebi.ac.uk/gwas/efotraits/EFO_0004582

our gwas catalog automat doesn't seem to have this identifier at all.

**Comment by cbizon** [comment]
It also seems that there are no variant-phenotype edges? @EvanDietzMorris is that right?

**Comment by EvanDietzMorris** [comment]
It seems our current GWASCatalog automat is out of date and/or broken - the current version has 10-12 edges with EFO:0004582. I'm not sure I understand the second question - the source data is parsed as variant --DiseaseOrPhenotypicFeature but normalization can alter the type of the disease/phenotype nodes.

**Comment by cbizon** [comment]
Yeah, for the second part, I ran this cypher: 
```
{
  "query": "MATCH (n)-[x]->(p) RETURN labels(n),labels(p),count(*)"
}
```
And found that there are gene-variant edges, and a few gene-gene edges (don't know where those come from) but no gene-diseaseorphenotypic feature edges (or anything else)

**Comment by cbizon** [comment]
So it seems like we need to push the new version to automat.

**Comment by EvanDietzMorris** [comment]
Oh wow - obviously that is not correct for any version of gwas catalog. The gene-variant edges come from supplementation (SNPEFF), and the gene-gene edges from OntologicalHierarchy (there should be disease-disease subclass edges as well unless they didn't load), but it appears the merge with OntologicalHierarchy did not work successfully when that Automat graph was made, and all of the actual gwas catalog edges were left out. That was done outside of Data Services and shouldn't happen again.
