### ISSUE TITLE
PMIDs on CTD edges?

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/ORION#142]
On robokopkg, I ran a query:
match (a:`biolink:Gene`)-[b:`biolink:increases_response_to`]->(c:`biolink:SmallMolecule`) return * limit 10

I get an edge between atorvastatin and TNFSF10.  But there's no PMID support on it:
![image](https://user-images.githubusercontent.com/10744350/205459062-cc7ea0b2-3fe4-4c1c-ba24-6f601f09c8cd.png)

Looking in CTD itself, there should be one publication that gets included.

**Comment by EvanDietzMorris** [comment]
We had PMIDs on a lot of the edges but were never getting them for gene to chemical edges due to a bug.. bug is fixed but graphs need to be rebuilt.
