### ISSUE TITLE
biolink:ameliorates_condition is still present in ROBOKOP KG

### ISSUE THREAD

**Issue by james0032** [RobokopU24/ORION#248]
I open this issue to discuss whether the predicate `biolink:ameliorates_condition` should be removed or not.
![image](https://github.com/user-attachments/assets/ad645baf-271a-4440-9d49-4245373dada2)

**Comment by EvanDietzMorris** [comment]
Ameliorates condition is valid: https://github.com/biolink/biolink-model/blob/e2a5167acf1a9bea9574724e3a9c2b3086649ced/biolink-model.yaml#L3357

"ameliorates" is not.. I think we can close this? Reopen if I'm missing something.
