### ISSUE TITLE
invalid provenance sources

### ISSUE THREAD

**Issue by cbizon** [RobokopU24/ORION#97]
https://github.com/ranking-agent/aragorn/issues/39

We have a number of provenance sources where we are putting a string rather than an "infores:" curie.  We need to clean those up.   Cleaning up may mean working with Matt Brush and others to mint new curies.

**Comment by cbizon** [comment]
This is a subtask of Graph Validation

**Comment by EvanDietzMorris** [comment]
there is another more specific issue about this
